# Generated by Django 4.0.5 on 2022-07-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('last_oil_check', models.DateTimeField()),
            ],
        ),
    ]
